mythos_website_upgrade/characterbirther/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.conf import settings

from . import views

from .views import BuildWizard

urlpatterns = [  
    url(r'^$', TemplateView.as_view(template_name='characterbirther/main.html')),
#    url(r'^build$', views.browse_options, name='make_investigator'),
    url(r'^build/(?P<step>[a-z]{0,10})$', BuildWizard.as_view(url_name='build_step'), name='build_step'),
    url(r'^character/(.{7})$', views.finished_character, name='finished_character '),
    url(r'^test_result$', TemplateView.as_view(template_name='characterbirther/debug_success.html')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mythos_website_upgrade/mythos_website_upgrade/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('characterbirther.urls')),
]

mythos_website_upgrade/characterbirther/models.py
from django.db import models
from randomslugfield import RandomSlugField
from birthcharacter.models import AbilityList, OccupationList, DriveList, RevisionStatus


#BirthForm model is responsible for holding the created player characters
class BirthForm(models.Model):
    birthcode = RandomSlugField(length=7, primary_key = True)
    name = models.CharField(max_length = 50)
    occupation = models.ForeignKey(
        OccupationList,
        on_delete = models.PROTECT,
        blank = True,
        null = True
    )
    drive = models.ForeignKey(
        DriveList,
        on_delete = models.PROTECT,
        blank = True,
        null = True
    )
    birthplace = models.CharField(
#        'the place where the Investigator was born',
        max_length = 50,
        blank = True,
        null = True
    )
    age = models.IntegerField(blank = True, null = True)
    PRONOUN_CHOICES = (
        ('Y', 'they/them/theirs'),
        ('M', 'he/him/his'),
        ('F', 'she/her/hers')
    )
    pronoun = models.CharField(
        'Preferred pronouns',
        max_length = 1,
        choices = PRONOUN_CHOICES,
        )
    confirm_start = models.BooleanField('investigator created', default = False)
    confirm_drive = models.BooleanField('drive selection completed', default = False)
    confirm_occupation = models.BooleanField('occupation selection completed', default = False)
    confirm_pillars = models.BooleanField('pillars of sanity selection completed', default = False)
    confirm_sources = models.BooleanField('sources of sanity selection completed', default = False)
    confirm_abilities = models.BooleanField('character background completed', default = False)
    confirm_done = models.BooleanField('birth complete', default = False)

#InnateAbility model is responsible for holding the values of created players skills
class InnateAbility(models.Model):
    character_id = models.ForeignKey(
        BirthForm,
        on_delete = models.CASCADE
    )
    ability = models.ForeignKey(
        AbilityList,
        on_delete = models.PROTECT
    )
    value = models.IntegerField()

#the session model
class Session(models.Model):
    sessioncode = models.CharField(
        'the affectionate name of the session', 
        max_length=25, 
        primary_key = True
    )
    investigators = models.ManyToManyField(BirthForm)
    date = models.DateField('the date the session took place')
    plot = models.TextField('what happened during the session?')

#Campaign model is the responsible for holding the information describing what happened in each campaign, with a MAX of 5 player characters but perhaps with more and max of 3 sessions.
class Campaign(models.Model):
    campaigncode = models.CharField(
        'the affectionate name of the campaign in which unites characters on a Spine',
        max_length = 25,
        primary_key = True,
    )
    session1 = models.OneToOneField(
        Session,
        on_delete = models.PROTECT,
        blank = True,
        related_name = 'first_session_of'
    )
    session2 = models.OneToOneField(
        Session,
        on_delete = models.PROTECT,
        blank = True,
        related_name = 'second_session_of'
    )
    session3 = models.OneToOneField(
        Session,
        on_delete = models.PROTECT,
        blank = True,
        related_name = 'third_session_of'
    )
    synopsis = models.TextField('a short description of the campaign: what changed, if anything, in the world?')
    complete = models.BooleanField('campaign complete')

#SanityPillars model is responsible for holding the created players pillars of sanity
class SanityPillars(RevisionStatus):
    investigators = models.ForeignKey(
        BirthForm,
        on_delete = models.PROTECT
    )
    pillar = models.CharField('pillar of sanity',max_length=30)
    description = models.TextField(
        'a short description of this pillar of sanity',
        blank = True
    )

#StabilitySources model is responsible for holdng the created players sources of stability, could this area be expanded a little to involve these as more stable NPCs?
class StabilitySources(RevisionStatus):
    investigators = models.ForeignKey(
        BirthForm,
        on_delete = models.PROTECT
    )
    name = models.CharField('the Name of this source of stability', max_length = 50)
    residence = models.CharField(
        'where this source lives',
        max_length = 50,
        blank = True
    )
    relation = models.CharField('the relationship between the investigator and this source of stability', max_length = 50)
    personality = models.TextField(
        'a short description of the personality of this character',
        blank = True)

mythos_website_upgrade/characterbirther/forms.py
from django.forms import ModelForm, inlineformset_factory, HiddenInput, ModelChoiceField
from .models import BirthForm, SanityPillars, InnateAbility, StabilitySources

class CharBirthForm(ModelForm):
    class Meta:
        model = BirthForm
        fields = ['name', 'pronoun', 'age', 'birthplace', 'drive', 'occupation']

'''
#(1) no from previous mistake where each thing  was it' own form  instead of a single super big form
class CharBirthForm(ModelForm):
    class Meta:
        model = BirthForm
        fields = ['name', 'pronoun', 'age', 'birthplace']
#        widgets = {'birthcode' : HiddenInput()}
#        widgets = {'confirm_start' : HiddenInput()}

class DriveForm(ModelForm):
    class Meta:
        model = BirthForm
        fields = ['drive']
#        widgets = {'confirm_drive' : HiddenInput()}


class OccupationForm(ModelForm):
    class Meta:
        model = BirthForm
        fields = ['occupation']
#        widgets = {'confirm_occupation' : HiddenInput()}

#(2) no longer need to define the modelform explicitly, it's made from the inlineformset_factory 

class SanityForm(ModelForm):
    class Meta:
        model = SanityPillars
        fields = ['pillar', 'description']

#commenting out the confirm fields!
#        def __init__(self, *args, **kwargs):
#            super(DocumentForm, self).__init__(*args, **kwargs)
#            self.fields['confirm_pillars'] = BooleanField(queryset=BirthForm.objects['confirm_pillars'])
#            self.fields['FORCE_confirm_pillars'] = True

#        widgets = {'confirm_pillars' : HiddenInput()}

class AbilitiesForm(ModelForm):
    class Meta:
        model = InnateAbility
        fields = ['ability', 'value']

class SourceBirthForm(ModelForm):
    class Meta:
        model = StabilitySources
        fields = ['name', 'relation', 'personality', 'residence']
'''

#formset for pillars of sanity
PillarsOfSanity = inlineformset_factory(
    BirthForm,
    SanityPillars, 
    fields = ['pillar', 'description'],
    extra = 0,
    min_num = 1, 
    max_num = 3, 
    can_delete = True, 
    validate_min = True, 
    validate_max = True,
    )

#formset for abilities
Abilities = inlineformset_factory(
    BirthForm,
    InnateAbility,
    fields = ['ability', 'value'],
    can_delete=True,
    )

#formset for sources of Stability
SourcesOfStability = inlineformset_factory(
    BirthForm,
    StabilitySources,
    fields = ['name', 'relation', 'personality', 'residence'],
    extra = 0,
    min_num = 1,
    max_num = 4,
    can_delete = True,
    validate_min = True, 
    validate_max = True,
    )

mythos_website_upgrade/characterbirther/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import DetailView, ListView

#gotta import the ManagementForm to be able to redefine the get_context_data for the wiazard view
from formtools.wizard.views import NamedUrlSessionWizardView, ManagementForm

#models and forms used in this view
from birthcharacter.models import OccupationList, AbilityList, DriveList, AssociatedOccuAbil, AssociatedOccuDrive
from characterbirther.models import BirthForm
from characterbirther.forms import CharBirthForm, PillarsOfSanity, Abilities, SourcesOfStability

#for passing character options data from the models
DATA_ALIASES = {'occupations' : OccupationList.objects.all().order_by('occupation'),
                'abilities' : AbilityList.objects.all().order_by('ability'),
                'I_abilities' : AbilityList.objects.filter(major_type='I').order_by('ability'),
                'G_abilities' : AbilityList.objects.filter(major_type='G').order_by('ability'),
                'drives' : DriveList.objects.all().order_by('drive'),
                'recommended_occupations' : AssociatedOccuAbil.objects.all(),
                }

#for rendering each wizard form in a different template
TEMPLATES =  {'start' : 'characterbirther/choose_base.html',
              'drive' : 'characterbirther/choose_psych.html',
              'pillars' : 'characterbirther/choose_pillars.html',
              'occupation' : 'characterbirther/choose_occupations.html',
              'abilities' : 'characterbirther/choose_abilities.html',
              'circle' : 'characterbirther/choose_circle.html',
#              'confirm' : 'characterbirther/character_confirm.html'
                }

#different fields for the different templates to render of CharBirthForm
DISPLAY_LISTS =  {'start' : ['name', 'pronoun', 'age', 'birthplace'],
                  'drive' : ['drive'],
#                  'pillars' : 'characterbirther/choose_pillars.html',
                  'occupation' : ['occupation'],
#                  'abilities' : 'characterbirther/choose_abilities.html',
#                  'circle' : 'characterbirther/choose_circle.html',
#                  'confirm' : 'characterbirther/character_confirm.html'
                  }

#the progression for the wizard
NAMED_FORM_LIST = [("start", CharBirthForm),
                   ("drive", CharBirthForm),
                   ("pillars", PillarsOfSanity),
                   ("occupation", CharBirthForm),
                   ("abilities", Abilities),
                   ("circle", SourcesOfStability),
                   ]

'''
#a list of things form some reason at some point in my sortid django learning process
HIDDEN_INITIAL_FLAG =  {
    'start' : {'confirm_start' : True},
    'drive' : {'confirm_drive' : True},
    'pillars' : {'confirm_pillars' : True},
    'occupation' : {'confirm_occupation' : True},
    'abilities' : {'confirm_abilities' : True},
    'circle' : {'confirm_circle' : True},
    }
'''

'''
#browse options and create a character
def browse_options(request):
    form = CharBirthForm()
    return render(request,'characterbirther/make_investigator.html', DATA_ALIASES)
'''

class BuildWizard(NamedUrlSessionWizardView):
    form_list = NAMED_FORM_LIST
#    initial_dict = HIDDEN_INITIAL_FLAG

    def get_context_data(self, form, **kwargs):
        context = super(BuildWizard, self).get_context_data(form=form, **kwargs)
        context.update(self.storage.extra_data)
        context['wizard'] = {
            'form': form,
            'steps': self.steps,
            'management_form': ManagementForm(prefix=self.prefix, initial={
                'current_step': self.steps.current,
            }),
        }

        #pass character option contexts only when needed, in the future make this more specific, also update the BirthForm derived forms with the display fields for the different wizard renderings
        if context['step'] == 'pillars':
            return context
        elif context['step'] == 'circle':
            return context
        else:
            context.update(DATA_ALIASES)
            if context['step'] == 'start':
                context.update({'display_start' : DISPLAY_LISTS['start']})
                return context
            elif context['step'] == 'drive':
                context.update({'display_drive' : DISPLAY_LISTS['drive']})
                return context
            elif context['step'] == 'occupation':
                context.update({'display_occupation' : DISPLAY_LISTS['occupation']})
                #return context
            else:
                return context
                
    #to render a different template for different pieces of each form
    def get_template_names(self):
        return [TEMPLATES[self.steps.current]]

    #to save the form and specify the done state
    def done(self, form_list, form_dict, **kwargs):
        #debug
        import pdb, pprint; pdb.set_trace()
        birthcharacter = BirthForm.save(commit=False)
        for form, instance in form_dict.items():
            print(instance)
            return birthcharacter
        birthcharacter.save()
        return HttpResponseRedirect(self.request, 'test_result')

#the finished character view displays all the characters choices for a final one page editing
def finished_character(request):
    form = CharBirthForm(request.POST)
    return render(request, 'characterbirther/make_investigator.html', {'abilities' : Abilities})

'''
junk code
some general view templates that are over your head at the moment

class Occupations(ListView):
    model = OccupationList
    template_name = 'characterbirther/make_investigator.html'
    
    def get_context_data(self ,**kwargs):
        # Call the base using super to access the context data
        context = super(Occupations,self).get_context_data(**kwargs)
        # Assign data to the context data
        context['occupational_abilities'] = AssociatedOccuAbil.objects.all()
        return context

class CharacterOptionsView(DetailView):
    model = OccupationList
    template_name = 'characterbirther/make_investigator.html'
    
    def get_context_data(self ,**kwargs):
        # Call the base using super to access the context data
        context = super(CharacterOptionsView,self).get_context_data(**kwargs)
        # Assign data to the context data
        context['occupational_abilities'] = AssociatedOccuAbil.objects.all()
        return context

a line of code to filter some things out from the database        
#DriveList.objects.filter(associatedoccudrive__drive = 'Antiquarian')

    #to process the form data between each step add flags as a dict to data for completion
    def get_form_step_data(self, form):
        confirm_step = 'confirm_' + form.data['build_wizard-current_step']
        form = form.data.update({confirm_step : True})
        return form.data
'''

mythos_website_upgrade/characterbirther/templates/characterbirther/ability_options.html
<!-- ABILITY CONTENT ACCORDION -->
  <div onclick="myAccordian('ability')" class="bgimg-3 w3-btn w3-bar w3-section">
    <span class="w3-left w3-large w3-wide w3-text-light-grey">Abilities</span>
    <span class="w3-right w3-text-light-grey"><i class="fa fa-caret-down"></i></span>
  </div>

<!-- INVESTIGATIVE ABILITY CONTENT -->    
  <div id="ability" class="w3-hide w3-container">
    <div>
      <div>
        <h2>Investigative Abilities</h2>
      </div>
      {% for ability in I_abilities %}
      <div class="w3-half listitem">
        <a href="/JS_use.html" onclick="popON('{{ ability }}'); return false;" class="w3-wide w3-large">{{ ability }}</a>
        <span class="w3-button w3-circle w3-ripple"><i class="fa fa-plus" aria-hidden="true"></i>
      </div>
    
<!-- INVESTIGATIVE ABILITY MODAL -->
      <div id="{{ ability }}" class="w3-modal w3-round-large">
        <div class="w3-modal-content w3-card-4">
          <header class="w3-container w3-dark-grey"> 
            <span onclick="popOFF('{{ ability }}')" class="w3-button w3-display-topright">&times;</span>
            <h2>{{ ability }} ({{ ability.investigative_type }})</h2>
          </header>
          <div class="w3-container">
            <p>{{ ability.description }}</p>
            
            <h5>Associated Occupations</h5>
            {% for occupation in ability.associatedoccuabil_set.all %}
            <p>{{ occupation.associated_occupations_id }}</p>
            {% endfor %}
          </div>
          <footer class="w3-container w3-dark-grey w3-padding">
            <span class="w3-button w3-round w3-ripple"><i class="fa fa-plus" aria-hidden="true"></i>Add this drive to character cart</span>
          </footer>
        </div>
      </div>          
      {% endfor %}
    </div>

<!-- GENERAL ABILITY CONTENT -->     
    <div>
      <div>
        <h2>General Abilities</h2>
      </div>
      {% for ability in G_abilities %}
      <div class="w3-half listitem">
        <a href="/JS_use.html" onclick="popON('{{ ability }}'); return false;" class="w3-wide w3-large">{{ ability }}</a>
        <span class="w3-button w3-circle w3-ripple"><i class="fa fa-plus" aria-hidden="true"></i>
      </div>
    
<!-- GENERAL ABILITY MODAL -->
      <div id="{{ ability }}" class="w3-modal w3-round-large">
        <div class="w3-modal-content w3-card-4">
          <header class="w3-container w3-dark-grey"> 
            <span onclick="popOFF('{{ ability }}')" class="w3-button w3-display-topright">&times;</span>
            <h2>{{ ability }} ({{ ability.investigative_type }})</h2>
          </header>
          <div class="w3-container">
            <p>{{ ability.description }}</p>
            
            <h5>Associated Occupations</h5>
            {% for occupation in ability.associatedoccuabil_set.all %}
            <p>{{ occupation.associated_occupations_id }}</p>
            {% endfor %}
          </div>
          <footer class="w3-container w3-dark-grey w3-padding">
            <span class="w3-button w3-round w3-ripple"><i class="fa fa-plus" aria-hidden="true"></i>Add this drive to character cart</span>
          </footer>
        </div>
      </div>          
      {% endfor %}    
    </div>
    
<!-- ABILITY COLLAPSE -->
    <div onclick="myAccordian('ability')" class="w3-container w3-dark-grey w3-bar w3-button w3-ripple">
      <div class="w3-tiny w3-left w3-wide">collapse Ability options</div>
      <div class="w3-small w3-right"><i class="fa fa-caret-up"></i></div>
    </div>
  </div>

mythos_website_upgrade/characterbirther/templates/characterbirther/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<meta charset="utf" />
<title>{% block title %}This is the title of the page{% endblock title %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Averia Sans Libre">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="http://www.w3schools.com/w3css/4/w3.css">

<link rel="stylesheet" href="{% static "w3_backup.css" %}">
<link rel="stylesheet" href="{% static "custom_mods.css" %}">


{% block head %}{% endblock head %}

</head>

<!-- css fallback, mostly for offline development
<script type="text/javascript">
$.each(document.styleSheets, function(i,sheet){
  if(sheet.href=="http://www.w3schools.com/w3css/4/w3.css") {
    var rules = sheet.rules ? sheet.rules : sheet.cssRules;
    if (rules.length == 0) {
      $('<link rel="stylesheet" type="text/css" href="{% static w3_backup.css %}">').appendTo('head');
    }
 }
})
</script>
 -->
 
{% block watermark %}{% endblock watermark %}

<style>
/* Create a Parallax Effect */
.bgimg-1, .bgimg-2, .bgimg-3, .bgimg-4 {
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}

/* First image (Logo. Full height) */
.bgimg-1 {
    background-image: url("{% static "images/regio_tall2.png" %}");
    min-height: 100%;
}

/* Second image (Contact) */
.bgimg-2 {
    background-image: url("{% static "images/toronto_dread2.png" %}");
    min-height: 60%;
}

/* Third image (Game) */
.bgimg-3 {
    background-image: url("{% static "images/jupiters_eye2.png" %}");
    min-height: 60%;
}

/* Fourth image (Contact) */
.bgimg-4 {
    background-image: url("{% static "images/closeup_painting2.png" %}");
    min-height: 60%;
}
/* Fifth image (Footer tentacles) */
.bgimg-5 {
    background-image: url("{% static "images/tentacle_field.svg" %}");
    min-width: 100%;
    min-height: 400px;
}
</style>

<body>
{% block topnav %}

<!-- Navbar -->
<div class="w3-top" id="nav">

  <div class="w3-top w3-bar w3-black w3-card-2 w3-left-align">
    <a class="w3-padding-large w3-hide-medium w3-hide-large w3-bar-item w3-button w3-right" href="javascript:void(0)" onclick="toggleShow('navDemo')" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="#about" class="w3-padding-large w3-hide-small w3-bar-item w3-button">ABOUT</a>
    <a href="#game" class="w3-padding-large w3-hide-small w3-bar-item w3-button">GAME</a>
    <a href="#story" class="w3-padding-large w3-hide-small w3-bar-item w3-button">STORY</a>
    <!-- the play button remains in small views -->
    <a href="#contact" class="w3-padding-large w3-bar-item w3-button">PLAY</a>
    <div class="w3-hide-small w3-dropdown-click">
      <button onclick="toggleShow('dropmenu')" class="w3-padding-large w3-button">Details <i class="fa fa-caret-down"></i></button>
      <div id="dropmenu" class="w3-dropdown-content w3-bar-block w3-white w3-card-4">
        <a href="#game" class="w3-bar-item w3-button">GAME</a>
        <a href="#story" class="w3-bar-item w3-button">STORY</a>
        <a href="#" class="w3-bar-item w3-button">PARTICIPANTS</a>
      </div>
    </div>
  <!-- some day I'd like this to be visible no matter what in some sort of drop down menu perhaps -->
    <div class="w3-hide-medium w3-hide-small w3-right"> 
      <audio controls autoplay>
        <source src="{% static "sounds/Purist_Trail_of_Cthulhu_Theme2.mp3" %}" type="audio/mpeg"> Your browser does not support the audio element.
      </audio>
    </div>
  </div>

<!-- Navbar on small screens -->
  <div id="navDemo" class="w3-hide w3-hide-large w3-hide-medium w3-black w3-top" style="margin-top:46px">
    <a href="#about" class="w3-bar-item w3-button">ABOUT</a>
    <a href="#game" class="w3-bar-item w3-button">GAME DETAILS</a>
    <a href="#story" class="w3-bar-item w3-button">STORY DETAILS</a>
    <a href="#" class="w3-bar-item w3-button">PARTICIPANTS</a>
  </div>

</div>
{% endblock topnav %}

{% block activetext%}<div id="main"> <p>Hello, I am the active text block. Fill me with things that will be major</p> {% endblock %}

<!-- footer -->

{% block footer%}
<div class="bgimg-5 w3-display-container">
  <div class="w3-display-middle w3-padding-0" id="poem">
    <p class="w3-center"><a href="https://www.poetryfoundation.org/poems-and-poets/poems/detail/47536" style="text-decoration:none">Then practice losing farther, losing faster: <br> places, and names, and where it was you meant <br> to travel. None of these will bring disaster." <br> -Elizabeth Bishop</a></p>
  </div>
  <div class="w3-display-bottomright w3-container w3-right-align w3-tiny" style="line-height:1" id="copyright">
    <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/InteractiveResource" property="dct:title" rel="dct:type">meaningful acts</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://danwchan.ca" property="cc:attributionName" rel="cc:attributionURL">Daniel W Chan</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
  </div>
</div>
{% endblock footer%}

{% block scripts %}
<!-- javascript -->
<script src="{% static "scripts.js" %}"></script>
{% endblock scripts %}

</body>
</html>

mythos_website_upgrade/characterbirther/templates/characterbirther/cart_sidebar.html
<!-- now merged into the make_investigator template so this code is no longer relevant -->

<!-- this is the button to access the character 'cart' -->
  <div class="w3-display-right overlay">
    <button class="w3-button w3-ripple w3-black w3-large w3-round-xxlarge w3-padding-32 w3-opacity-max" onclick="toggleSidecol()" id="floatbtn">
      <i class="fa fa-user" aria-hidden="true"></i>
    </button>
  </div>

<!-- this is the character 'cart' -->
  <div class="w3-display-right w3-bar-block w3-grey w3-card-2 w3-mobile w3-animate-right w3-hide overlay" id="sidebar">
    <button class="w3-bar-item w3-button w3-large" onclick="toggleSidecol()">Close &times;</button>
    <a class="w3-bar-item w3-button" href="#">Link 1</a>
    <a class="w3-bar-item w3-button" href="#">Link 2</a>
    <a class="w3-bar-item w3-button" href="#">Link 3</a>
  </div>

mythos_website_upgrade/characterbirther/templates/characterbirther/character_confirm.html
{% extends "./make_investigator.html" %}

{% block title %}Investigator Creation: Confirmation{% endblock title%}

{% block topnav %}

<!-- Navbar -->
<div class="w3-display-container w3-top w3-black w3-center" id="nav"> 
    <div class="w3-left"> 
      <a href="/" class="w3-padding-16 w3-bar-item w3-button"><i class="fa fa-home"></i></a>
      <a href="/build/pillars" class="w3-padding-16 w3-bar-item w3-button"><i class="fa fa-undo"></i></a>
    </div>
    <a href="/build/drive" class="w3-hide-small w3-padding-16 w3-bar-item w3-button">DRIVE</a>
    <a href="/build/pillars" class="w3-hide-small w3-padding-16 w3-bar-item w3-button">PILLARS</a>
    <a href="/build/occupation" class="w3-padding-16 w3-bar-item w3-button">OCCUPATION</a>
    <a href="/build/abilities" class="w3-hide-small w3-padding-16 w3-bar-item w3-button">ABILITIES</a>
    <a href="/build/circle" class="w3-hide-small w3-padding-16 w3-bar-item w3-button">CIRCLE</a>
    <div class="w3-right"> 
      <a href="/build/abilities" class="w3-padding-16 w3-bar-item w3-button"><i class="fa fa-angle-double-right"></i></a>
    </div>
</div>

{% endblock topnav %}

{% block formbox %}

<form class="w3-container" method="post">
  {% csrf_token %}
<div class="w3-light-grey w3-border w3-display-container">   

  <h2>{{ form.name }}</h2>

  {% for field in form %}
    <div class="w3-section">
      {{ field.errors }}
      {{ field.label_tag }} {{ field }}
    </div>
  {% endfor %}

  <h2>Two</h2>

  {% for ability in form.innateability_set.all %}
    <div class="w3-section">
      {{ ability.ability_id }}
    </div>
  {% endfor %}

</div>

{% endblock formbox %}

mythos_website_upgrade/characterbirther/templates/characterbirther/debug_success.html
it worked, keep going!